<?php

namespace BrookinsConsulting\BcGitHubStarsBundle\Repository;

/**
 * GitHubRepositoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GitHubRepositoryRepository extends \Doctrine\ORM\EntityRepository
{
}
